In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('employee_data.csv')
df.head()

   Unnamed: 0  id groups  age  healthy_eating  active_lifestyle  salary
0           0   0      A   36               5                 5    2297
1           1   1      A   55               3                 5    1134
2           2   2      A   61               8                 1    4969
3           3   3      O   29               3                 6     902
4           4   4      O   34               6                 2    3574

In [4]:
df.drop(columns=['Unnamed: 0', 'id'], inplace=True)

In [5]:
df.shape

(1000, 5)

In [6]:
df.describe()

               age  healthy_eating  active_lifestyle      salary
count  1000.000000     1000.000000       1000.000000  1000.00000
mean     41.155000        4.944000          5.683000  2227.46100
std      13.462995        2.013186          2.048587  1080.20976
min      18.000000        0.000000          0.000000   553.00000
25%      30.000000        4.000000          4.000000  1360.00000
50%      41.000000        5.000000          6.000000  2174.00000
75%      53.000000        6.000000          7.000000  2993.75000
max      64.000000       10.000000         10.000000  5550.00000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   groups            1000 non-null   object
 1   age               1000 non-null   int64
 2   healthy_eating    1000 non-null   int64
 3   active_lifestyle  1000 non-null   int64
 4   salary            1000 non-null   int64
dtypes: int64(4), object(1)
memory usage: 39.2+ KB

In [8]:
df.isna().sum()

groups              0
age                 0
healthy_eating      0
active_lifestyle    0
salary              0
dtype: int64

In [9]:
def age_group(age):
    if 11<= age <=20:
        return '11-20'
    if 21<= age <=30:
        return '21-30'
    if 31<= age <=40:
        return '31-40'
    if 41<= age <=50:
        return '41-50'
    if 51<= age <=60:
        return '51-60'
    if 61<= age <=70:
        return '61-70'
    else:
        return 'unknown'

In [10]:
df['age_group'] = df['age'].apply(age_group)

In [11]:
df.head()

  groups  age  healthy_eating  active_lifestyle  salary age_group
0      A   36               5                 5    2297     31-40
1      A   55               3                 5    1134     51-60
2      A   61               8                 1    4969     61-70
3      O   29               3                 6     902     21-30
4      O   34               6                 2    3574     31-40

In [12]:
df.groupby(df['age_group'])[['salary','active_lifestyle']].mean()

                salary  active_lifestyle
age_group
11-20      2229.109375          5.171875
21-30      2324.333333          5.014706
31-40      2304.379808          5.822115
41-50      2218.848214          6.035714
51-60      2127.851852          5.773148
61-70      2079.583333          6.178571

In [33]:
df.groupby(df['age_group'])[['salary']].median()

           salary
age_group
11-20      2065.0
21-30      2297.0
31-40      2065.0
41-50      2176.5
51-60      2063.5
61-70      2065.0

In [34]:
df.groupby(df['age_group'])[['salary']].sum()

           salary
age_group
11-20      142663
21-30      474164
31-40      479311
41-50      497022
51-60      459616
61-70      174685

In [35]:
df.groupby(df['age_group'])[['salary']].std()

                salary
age_group
11-20      1048.873048
21-30      1110.805170
31-40      1114.288991
41-50      1067.144080
51-60       991.633342
61-70      1184.071852

In [36]:
df.groupby(df['age_group'])[['salary']].min()

           salary
age_group
11-20         779
21-30         553
31-40         553
41-50         553
51-60         553
61-70         553

In [37]:
df2 = pd.read_csv('IRIS.csv')
df2.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [41]:
df2.groupby(df2['species'])[['sepal_length','sepal_width','petal_length','petal_width']].mean()

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [42]:
df2.groupby(df2['species'])[['sepal_length','sepal_width','petal_length','petal_width']].median()

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               5.0          3.4          1.50          0.2
Iris-versicolor           5.9          2.8          4.35          1.3
Iris-virginica            6.5          3.0          5.55          2.0

In [43]:
df2.groupby(df2['species'])[['sepal_length','sepal_width','petal_length','petal_width']].std()

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa          0.352490     0.381024      0.173511     0.107210
Iris-versicolor      0.516171     0.313798      0.469911     0.197753
Iris-virginica       0.635880     0.322497      0.551895     0.274650

In [44]:
df2.groupby(df2['species'])[['sepal_length','sepal_width','petal_length','petal_width']].min()

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               4.3          2.3           1.0          0.1
Iris-versicolor           4.9          2.0           3.0          1.0
Iris-virginica            4.9          2.2           4.5          1.4