In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Boston.csv')
df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [7]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [14]:
x = df.drop(columns=['medv'])
y = df['medv']

In [18]:
x.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33

In [19]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(455, 13)
(455,)
(51, 13)
(51,)

In [30]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [31]:
predicted = model.predict(x_test)
predicted

array([31.05334338, 21.01851981, 24.87898589, 16.16289825, 19.32805891,
       42.42883435, 33.77399158, 15.03887911, 17.18664283, 35.09056063,
       27.76208856, 21.17250381, 17.84845209, 30.25124652, 19.62462777,
       32.84480741, 20.93824055, 15.63916971, 16.90321053, 16.64524075,
       23.88070273, 17.18746732, 32.4389033 , 32.67329469, 20.92667171,
       13.35022285, 20.6863843 , 21.81546848, 35.87377725, 19.3815932 ,
       17.62902839, 18.66077851, 21.6074324 , 30.23431974, 29.82968347,
       10.14010179, 20.60225895, 15.05448931, 24.79422736, 40.30013372,
       17.71071043, 24.12894754, 19.63931864, 16.61510801, 35.12777804,
       22.44381464, 24.87228554, 41.97068383, 33.70719525, 23.24462043,
       19.40118239])

In [32]:
mse = mean_squared_error( y_true=y_test, y_pred=predicted)
mse

14.847468519012919